-- Agent 开放平台核心表结构（PostgreSQL）
-- 完整设计说明见 docs/Agent开放平台_技术规格文档.md 第四章

CREATE TABLE capability (
    -- BY DEFAULT（而非 ALWAYS）是因为内置能力（builtin_capabilities.go）需要
    -- 显式写入固定 ID（1/2），和 orchestration-service 的内置 Tool 映射表对齐。
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            SMALLINT     NOT NULL, -- 1=tool 2=skill 3=agent
    name            VARCHAR(100) NOT NULL,
    publisher_id    BIGINT       NOT NULL,
    schema_json     JSONB,                 -- 输入输出 JSON Schema，提交审核前可为空
    mcp_endpoint    VARCHAR(255),          -- MCP Server 地址，动态发现用
    is_builtin      BOOLEAN      NOT NULL DEFAULT FALSE, -- true=平台内置能力，免 MCP 走进程内调用
    current_version VARCHAR(20),           -- 当前已上架版本号，完整历史见 capability_version 表
    status          SMALLINT     NOT NULL DEFAULT 1, -- 1待审核 2已上架 3已下线
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_capability_publisher ON capability (publisher_id);
CREATE INDEX idx_capability_type_status ON capability (type, status);
COMMENT ON TABLE capability IS '能力主表';

CREATE TABLE capability_version (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    capability_id BIGINT      NOT NULL,
    version       VARCHAR(20) NOT NULL, -- 语义化版本号
    changelog     TEXT,
    is_latest     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (capability_id, version)
);
COMMENT ON TABLE capability_version IS '能力版本表';

CREATE TABLE agent (
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name              VARCHAR(100) NOT NULL,
    owner_id          BIGINT       NOT NULL,
    config_json       JSONB        NOT NULL, -- 挂载能力列表 + Hook 配置 + Loop 模板
    version           VARCHAR(20)  NOT NULL,
    status            SMALLINT     NOT NULL DEFAULT 1, -- 1开发中 2已发布 3已下线
    max_depth         SMALLINT     NOT NULL DEFAULT 3, -- 子 Agent 最大递归深度
    model_provider_id BIGINT,                -- 引用 model_provider.id，决定该 Agent 用哪个模型供应商执行
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_agent_owner ON agent (owner_id);
COMMENT ON TABLE agent IS 'Agent 主表';

-- 表名：model_provider（用户自建的模型供应商配置）
-- 对应实现计划里的人工决策：模型接入不写死单一供应商，而是让用户在前端自建
-- provider（含 API Key），Agent 发布时选择使用哪个 provider。归属 orchestration-service。
CREATE TABLE model_provider (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_id       BIGINT       NOT NULL,
    name           VARCHAR(100) NOT NULL, -- 用户自定义的供应商别名
    provider_type  SMALLINT     NOT NULL, -- 1=openai_compatible 2=anthropic
    base_url       VARCHAR(255),          -- OpenAI 兼容类型必填，Anthropic 可选（默认官方端点）
    model_name     VARCHAR(100) NOT NULL, -- 实际请求时使用的模型名
    api_key_cipher BYTEA        NOT NULL, -- AES-GCM 对称加密后的 API Key 密文
    status         SMALLINT     NOT NULL DEFAULT 1, -- 1启用 2已禁用
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_model_provider_owner ON model_provider (owner_id);
COMMENT ON TABLE model_provider IS '模型供应商配置表';

CREATE TABLE agent_run (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    agent_id      BIGINT      NOT NULL,
    channel       SMALLINT    NOT NULL, -- 1=api 2=workbench
    trace_id      VARCHAR(64) NOT NULL,
    caller_key_id BIGINT,               -- 发起调用的 API Key，Workbench 场景为空
    tokens_used   INT         NOT NULL DEFAULT 0,
    status        SMALLINT    NOT NULL, -- 1成功 2失败 3限流拒绝
    started_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_agent_run_agent_time ON agent_run (agent_id, started_at);
CREATE INDEX idx_agent_run_trace ON agent_run (trace_id);
COMMENT ON TABLE agent_run IS 'Agent 运行记录表';

CREATE TABLE api_key (
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    developer_id BIGINT      NOT NULL,
    key_prefix   VARCHAR(12) NOT NULL, -- 展示用前缀，如 sk-abc1
    key_hash     VARCHAR(64) NOT NULL, -- Key 的哈希值，不存明文
    scopes       JSONB       NOT NULL, -- 如 ["agent:123:invoke"]
    status       SMALLINT    NOT NULL DEFAULT 1, -- 1启用 2已吊销
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (key_hash)
);
CREATE INDEX idx_api_key_developer ON api_key (developer_id);
COMMENT ON TABLE api_key IS '开发者 API Key 表';

CREATE TABLE subscription (
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    consumer_agent_id BIGINT      NOT NULL, -- 发起挂载的 Agent（Hub）
    capability_id     BIGINT      NOT NULL, -- 被挂载的能力（Tool/Skill/Agent）
    pinned_version    VARCHAR(20) NOT NULL, -- 锁定版本，默认不跟随最新
    status            SMALLINT    NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (consumer_agent_id, capability_id)
);
COMMENT ON TABLE subscription IS '能力挂载订阅表';

CREATE TABLE usage_record (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    agent_run_id  BIGINT      NOT NULL,
    capability_id BIGINT,              -- 若该次消耗来自某个被调用能力，记录归属
    tokens        INT         NOT NULL DEFAULT 0,
    cost_cents    INT         NOT NULL DEFAULT 0,
    revenue_share INT         NOT NULL DEFAULT 0, -- 分给能力提供方的金额（分）
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_usage_record_run ON usage_record (agent_run_id);
CREATE INDEX idx_usage_record_capability ON usage_record (capability_id);
COMMENT ON TABLE usage_record IS '用量与分成记录表';
