// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/orchestration.proto

package orchestration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"` // 当前递归深度，Subagent 调用时 +1 传递
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InvokeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InvokeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *InvokeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type InvokeChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Usage         *UsageInfo             `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeChunk) Reset() {
	*x = InvokeChunk{}
	mi := &file_proto_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeChunk) ProtoMessage() {}

func (x *InvokeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeChunk.ProtoReflect.Descriptor instead.
func (*InvokeChunk) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InvokeChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *InvokeChunk) GetUsage() *UsageInfo {
	if x != nil {
		return x.Usage
	}
	return nil
}

type UsageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        int32                  `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageInfo) Reset() {
	*x = UsageInfo{}
	mi := &file_proto_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageInfo) ProtoMessage() {}

func (x *UsageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageInfo.ProtoReflect.Descriptor instead.
func (*UsageInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *UsageInfo) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

var File_proto_orchestration_proto protoreflect.FileDescriptor

const file_proto_orchestration_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orchestration.proto\x12\x17agentmesh.orchestration\"\x94\x01\n" +
	"\rInvokeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"|\n" +
	"\vInvokeChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x128\n" +
	"\x05usage\x18\x03 \x01(\v2\".agentmesh.orchestration.UsageInfoR\x05usage\"#\n" +
	"\tUsageInfo\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\x05R\x06tokens2p\n" +
	"\x14OrchestrationService\x12X\n" +
	"\x06Invoke\x12&.agentmesh.orchestration.InvokeRequest\x1a$.agentmesh.orchestration.InvokeChunk0\x01B/Z-github.com/agentmesh/shared/pkg/orchestrationb\x06proto3"

var (
	file_proto_orchestration_proto_rawDescOnce sync.Once
	file_proto_orchestration_proto_rawDescData []byte
)

func file_proto_orchestration_proto_rawDescGZIP() []byte {
	file_proto_orchestration_proto_rawDescOnce.Do(func() {
		file_proto_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestration_proto_rawDesc), len(file_proto_orchestration_proto_rawDesc)))
	})
	return file_proto_orchestration_proto_rawDescData
}

var file_proto_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_orchestration_proto_goTypes = []any{
	(*InvokeRequest)(nil), // 0: agentmesh.orchestration.InvokeRequest
	(*InvokeChunk)(nil),   // 1: agentmesh.orchestration.InvokeChunk
	(*UsageInfo)(nil),     // 2: agentmesh.orchestration.UsageInfo
}
var file_proto_orchestration_proto_depIdxs = []int32{
	2, // 0: agentmesh.orchestration.InvokeChunk.usage:type_name -> agentmesh.orchestration.UsageInfo
	0, // 1: agentmesh.orchestration.OrchestrationService.Invoke:input_type -> agentmesh.orchestration.InvokeRequest
	1, // 2: agentmesh.orchestration.OrchestrationService.Invoke:output_type -> agentmesh.orchestration.InvokeChunk
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_orchestration_proto_init() }
func file_proto_orchestration_proto_init() {
	if File_proto_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestration_proto_rawDesc), len(file_proto_orchestration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestration_proto_goTypes,
		DependencyIndexes: file_proto_orchestration_proto_depIdxs,
		MessageInfos:      file_proto_orchestration_proto_msgTypes,
	}.Build()
	File_proto_orchestration_proto = out.File
	file_proto_orchestration_proto_goTypes = nil
	file_proto_orchestration_proto_depIdxs = nil
}
